#server:
#  port: 7000
#spring:
#  cloud:
#    nacos:
#      server-addr: localhost:8848
#  application:
#    name: gulimall-coupon
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.188.129:3306/gulimail_ums?useSSL=false
#    password: root
#    username: root
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
